### ISSUE TITLE
Error when installing: `The extension Confetti is not valid` 

### ISSUE THREAD

**Issue by Lextuga007** [ArthurData/quarto-confetti#2]
I get the error: `ERROR: The extension Confetti is not valid- it does not contribute anything.` when I run the code `quarto install extension ArthurData/quarto-confetti` from the README.

**Comment by ArthurData** [comment]
Hello @Lextuga007 , 

Sorry to see that.
Can you tell me more about your local environment (OS, version, Quarto version)? 

Thank you

**Comment by Lextuga007** [comment]
Of course, I'm using Windows 10, Quarto 1.2 in RStudio 2022.07.2 with R version 4.2.1.

**Comment by ArthurData** [comment]
Hello @Lextuga007 , 
Can you try to update your version of Quarto to the latest version? 

I think I need to fix the minimum version :)

**Comment by Lextuga007** [comment]
Strangely it says the version is 1.2 in the packages information in RStudio but running `quarto::quarto_version()` it says 1.1.189. I've tried to install.packages but it hasn't updated so it might be that I haven't got the latest after all.

**Comment by ArthurData** [comment]
You can try to reinstall from Quarto documentation: https://quarto.org/docs/get-started/

**Comment by Lextuga007** [comment]
😊 that worked! So sorry as I was trying to update quarto as a package, not from this link! Bit new to quarto and hadn't fully appreciated (as in read) all the documentation! Thanks for replying - much appreciated.

**Comment by ArthurData** [comment]
Great! I'll take this opportunity to update the readme with the required version.
